# hostname (and path) to the root
baseURL: "https://learnvanillajs.com"

# Site title
title: "Learn JavaScript"

# Customer parameters
params:
  description: "A JavaScript course and ebook for beginners. Build your first JavaScript library in a few hours."
  api: "https://gomakethings.com/api/data.json"
  sales: "https://gomakethings.com/checkout/wp-json/gmt-edd/v1/sales?category=learnjs&start=02-01-2022&round=10&96gdGDPqokbFsy3Lbx7LwTBdYNDxpo4a=GbwzXPHRqqCDKyy38TYmAybvV8AZZUJHmuA8zKKMjJ2ZUXFG7LcCy2rLAMmU8HEZ"
  rssURL: ""
  rssLimit: 7
  minify: true

# Caches
caches:
  getjson:
    maxAge: "1m"

# The language code for the site
languageCode: "en-us"

# theme to use (located by default in /themes/THEMENAME/)
theme: "gmt"

Language:
  LanguageName: "English"

# Permalinks
# See "content-management/permalinks"
permalinks:
  course: /:filename/

# Use absolute URLs
canonifyURLs: true

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "hugoGeneratorInject", "404"]

# Files to ignore while rendering
ignoreFiles: []

# the length of text to show in a .Summary
summaryLength: 70

# Pagination
paginate: 35
paginatePath: "page"

# Markdown Options
blackfriday:
  fractions: false

# Syntax Highlighting
pygmentsCodefences: true
pygmentsUseClasses: true